title: "charliekendall.co.uk"
baseurl: ""
github_username: charliejkendall
full_name: "Charlie Kendall"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/:num/"

permalink: none

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
